# Site settings
title: JS Blog
url: "https://jsblog-xyz.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
#timezone: Asia/Chongqing
description: js blog, javascript blog, full stack blog, react, reactjs, vue, vuejs

# Your information
email: jsblog.xyz@gmail.com
author: JS Blog
avatar: "//www.gravatar.com/avatar/d1a815cf34bba450000181b7e0cc1079?d=mm&s=135"
profile:  All about javascript.
twitter_username: https://twitter.com/jsblog2
github_username:  https://github.com/jsblog-xyz

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
disqus_shortname: fuckit-1
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
